### ISSUE TITLE
Speedup unit tests

### ISSUE THREAD

**Issue by scls19fr** [RaspberryPi-Samples/py-my-key#15]
Unit tests are quite slow because of delay with lock

setting `time_opened` using in `test_000_something`

        my_app.hw.lock.time_opened = 0

could fix it

**Comment by scls19fr** [comment]
`BaseReader` have some `time.sleep` calls
https://github.com/RaspberryPi-Samples/py-my-key/blob/Led_management/py_my_key/readers.py

We should define at `initialize` a `time_to_sleep` (or `tts`) attribute.

`TestReader` should have `time_to_sleep` (or `tts`) attribute set to `0`.

**Comment by lwalter86** [comment]
tts is set
