### ISSUE TITLE
Led management

### ISSUE THREAD

**Issue by lwalter86** [RaspberryPi-Samples/py-my-key#18]
Need to implement led management

**Comment by scls19fr** [comment]
We need to wonder if we still want to use `Led` class from `pingo.parts.led` or have our own `Led` class.

Will we use `threading.Thread` to manage blinking led for example ? not sure that's a great idea. We might follow [KISS principle](https://en.wikipedia.org/wiki/KISS_principle). No threading might help.

After making our own non-threading `Led` class we might be able to merge code from `pingo.parts.led` to ours and provide a non threading and a threading class for Led (with a similar interface but with a different implementation)

**Comment by lwalter86** [comment]
We need to use threading because we want led blinking while waiting for another card (after passing a master card for example).

**Comment by lwalter86** [comment]
green Led is turned on while the door is open
Led blinking seems not to work as we want

**Comment by scls19fr** [comment]
[SMYC](http://www.acronymfinder.com/Slang/SMYC.html) ;-) 

You should make a branch and we will merge it when it will be fixed

**Comment by lwalter86** [comment]
See the branch [Led_management](https://github.com/RaspberryPi-Samples/py-my-key/tree/Led_management)
The time sleep in [readers.py](py-my-key/py_my_key/readers.py) seems to fix this issue but this needs to be confirmed.

**Comment by scls19fr** [comment]
Nice to see this branch merged!
