### ISSUE TITLE
WiringPi error

### ISSUE THREAD

**Issue by lwalter86** [RaspberryPi-Samples/py-my-key#19]
An error occurs a few minutes after we launch the script : 

```
" WiringPiSetup : unable to open /dev/mem : too many open files "
```

**Comment by scls19fr** [comment]
This could help
https://www.raspberrypi.org/forums/viewtopic.php?t=56496&p=427033
http://stackoverflow.com/questions/27376914/python-best-way-to-create-infinitive-loop-without-a-crash

**Comment by lwalter86** [comment]
NXP Explore-NFC reader doesn't use the Raspberry Pi pins we use to manage leds or buttons

**Comment by scls19fr** [comment]
A (quite dirty) workaround might be to run python script inside a Bash loop

```bash
until python cli_rpi_access.py; do
  echo Script failed, retrying in 2 seconds...
  sleep 2
done
```

http://serverfault.com/questions/80862/bash-script-repeat-command-if-it-returns-an-error

**Comment by scls19fr** [comment]
An other approach to consider might be to update WiringPi http://wiringpi.com/download-and-install/ and its Python wrapper https://github.com/WiringPi/WiringPi-Python

**Comment by scls19fr** [comment]
After updating WiringPi you should try

```
gpio -v
gpio readall
```

Reference: http://wiringpi.com/download-and-install/

**Comment by scls19fr** [comment]
Updating WiringPi Python wrapper may also be necessary

https://github.com/WiringPi/WiringPi-Python

**Comment by lwalter86** [comment]
I did it. It works fine.

**Comment by lwalter86** [comment]
I think i fund the error.
It is because of the nxppy.Mifare() function called in a loop in the [readers](py-my-key/py_my_key/readers.py) module

**Comment by scls19fr** [comment]
Great news!

One way to fix it could be to create an (empty) `initialize` method in `BaseReader` and to implement this `initialize` method in `NxppyReader`

```python

class BaseReader(Base):
    def initialize(self):
        pass

class NxppyReader(BaseReader):
    def initialize(self):
        self.mifare = nxppy.Mifare()

    def _read(self):
        data = ''
        try:
            data = self.mifare.select()
        except nxppy.SelectError:
            pass
        if data != '':
            return data
        else:
            return None
```

We will need to explicitly call this `initialize` method in [cli_rpi_access.py](https://github.com/RaspberryPi-Samples/py-my-key/blob/master/py_my_key/cli_rpi_access.py)

```python
    def create_reader(self):
        reader = self.Reader(comment='First reader')
        reader.initialize()
```

An other way could be to put `nxppy.Mifare()` in `__init__` but also call inherited class `__init__` method using `super(...)`.
I'm not sure about this second idea as `Base` is an SQLAlchemy object class... and there is probably some magical stuff around this ;-) so it should be heavily "tested" using some print calls.

**Comment by lwalter86** [comment]
The `initialise` method fix this issue but not in the `create_reader()` function.
I will consider this next week.

**Comment by lwalter86** [comment]
`create_reader()` is only executed at init : 
`sudo python py_my_key/cli_rpi_access.py --init` 

Or, we need to execute `nxppy.Mifare()` each time we start the application. So we have to put the `initialize()` call in the `run()` method of the app.

**Comment by scls19fr** [comment]
Yes you are right !

Thanks

**Comment by scls19fr** [comment]
You can probably now merge `Led_management` branch with `master` branch.
