### ISSUE TITLE
Continuous integration is failing because test run exceeded 120 minutes. 

### ISSUE THREAD

**Issue by scls19fr** [RaspberryPi-Samples/py-my-key#21]
See
https://travis-ci.org/RaspberryPi-Samples/py-my-key/builds/123866451

What are results of unit tests when run locally ?

**Comment by lwalter86** [comment]
I'm not patient enough to wait for the end of the test (more than 2 hours...).
Even after changing the waiting time for them to 0

(i did `sudo nosetests -s -v`, is that good ?)

**Comment by scls19fr** [comment]
Running tests on Travis seems to still be an infinite task !!!! It's not related to https://github.com/RaspberryPi-Samples/py-my-key/issues/15

**Comment by lwalter86** [comment]
this problem is caused by my small tests, especially the `blink_test.py` who ahs an infinite loop :-(
